language: python
python:
    - "3.6"
install:
    - pip3 install pipenv
    - pipenv install
script:
    - pipenv run pelican content
deploy:
  provider: pages
  repo: openclassmates/openclassmates
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
