language: python
python:
    - "3.6"
install:
    - pip3 install -r requirements.txt
script:
    - make publish
deploy:
  provider: pages
  repo: PythonClassmates/pythonclassmates.org
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
