language: python
python:
    - "3.6"
install:
    - pip3 install pipenv
    - pipenv install
script:
    - git clone https://github.com/alexandrevicenzi/Flex.git theme/active
    - pipenv run invoke publish
after_failure:
    - pipenv run invoke revert
deploy:
  provider: pages
  repo: PythonClassmates/pythonclassmates.org
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
