language: python
python:
    - "3.6"
install:
    - pip3 install pipenv
    - pipenv install
script:
    - pipenv run fab publish
after_failure:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false"  ]; then pipenv run fab revert; fi'
deploy:
  provider: pages
  repo: PythonClassmates/pythonclassmates.org
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
