language: python
python:
    - "3.6"
install:
    - pip3 install pipenv
    - pipenv install
script:
    - pipenv run pelican content
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output
